### ISSUE TITLE
Harden planner and orchestrator templates with proportional evidence and batched review

### ISSUE THREAD

**Issue by tonym999** [tonym999/vault-cleaner#144]
## Objective

Update the canonical planner and orchestrator templates so future tickets use evidence and review effort proportionate to risk, distinguish investigation from bounded development, avoid duplicated facts, and correct findings in coherent batches rather than creating repeated review/fix churn.

**Requirements source of truth:** this issue body, distilled from the review history of PR #143 and the owner discussion that followed it. PR #143 is evidence for the failure modes; it is not a template specification to copy verbatim.

This is issue creation only. Planning, repository edits, PR creation, merging, and changes to #141 require their applicable later authorisation.

## Why this is needed

PR #143 exposed a repeatable workflow failure rather than a single documentation typo:

- an investigative plan tried to record findings, prescribe their reproduction, and instruct a lower-tier implementer to rediscover them;
- extra specificity was used to compensate for implementation-model capability, but duplicated facts across context, required content, checklists, prompts, and worklog;
- shell examples were initially reviewed as prose rather than executed;
- narrow corrections introduced adjacent capture, shell-state, fail-open, and stale-sibling defects;
- incidental details such as exact source-read counts acquired stronger evidence machinery than the product decision required;
- a documentation-only plan grew to comparable complexity to an implementation.

The substantive safety findings were still valuable: missing versus empty loadout data, the Vault sentinel, identifier type boundaries, both finalisation call sites, private-data hygiene, and fail-closed evidence all affect downstream correctness.

## Relationship to existing workflow work

**Blocks #141.** Issue #141 packages the canonical workflow as reusable skills and requires those skills to keep repository templates as the single source of truth. These template corrections should land first so #141 does not package the failure modes observed in PR #143.

This issue does not implement skills, change skill packaging, or replace #141.

# Scope

## Planner template

Update `handoffs/templates/planner.md` to require:

1. **Task classification before detail.** Classify work as open-ended investigation, bounded experiment, normal development, cross-cutting safety work, or mechanical documentation. Model selection is driven primarily by unresolved uncertainty and safety risk, not file count or apparent change size.

2. **Capability-fit handling.** Do not compensate for a lower-capability investigative implementer by expanding the plan indefinitely. Choose one of:
   - allocate a model suitable for open-ended investigation;
   - reduce the work to a bounded experiment using a tested measurement harness and structured output;
   - split discovery from deterministic implementation.

3. **Evidence proportionality.** Classify empirical claims as:
   - decision-critical: reproducible command or authoritative source required;
   - supporting: source citation required, raw transcript optional;
   - incidental: omit unless it changes scope, safety, or a decision.

   Byte-for-byte reproduction is required only when bytes are part of the product or snapshot contract. Otherwise verification targets successful execution and decision-relevant fields or counts.

4. **Single-source facts.** Define each measured fact or settled decision once. Checklists and execution prompts reference that canonical section rather than restating values that can become stale.

5. **Executable evidence preflight.** Mark executable fences distinctly from illustrative pseudocode. Measurement blocks are atomic or explicitly standalone, run in the declared shell, fail closed, keep artifacts outside the tree, and include a representative negative-path check. Evidence is copied or generated mechanically from successful runs rather than hand-formatted.

6. **Planning at the right abstraction.**
   - Investigation plans specify questions, inputs, method, output schema, decision criteria, limitations, and stop conditions without pre-answering incidental findings.
   - Development plans specify behavior, invariants, seams, acceptance tests, migration/compatibility boundaries, and exclusions without prescribing unnecessary line-by-line implementation.

7. **Edge-case triage.** Record safety-critical, decision-relevant, and safely deferred cases. An edge case blocks planning only when it can affect user data, privacy, a protection rail, schema interpretation, irreversible output, a public compatibility contract, or the central ticket decision.

8. **Complexity check.** If a documentation-only plan approaches the complexity of its intended deliverable, simplify it or split the uncertainty before review.

Prefer stable file-and-symbol references over fragile line anchors when exact positioning is not material.

## Orchestrator template

Update `handoffs/templates/orchestrator.md` to require:

1. **Batched finding handling.** Collect a review round, group findings by root cause, and return one coherent correction batch to the implementer.

2. **Mechanism escalation.** When two findings involve the same mechanism, stop patching isolated examples. Require the implementer to consolidate, simplify, or return to the planner if the canonical plan must change.

3. **Sibling consistency sweep.** After changing a concept, search the complete diff and handoff for every repeated occurrence in context, scope, checklist, execution prompt, dispatch text, and worklog.

4. **Complete-diff preflight and re-review.** Rerun executable evidence, negative checks, repository gates, and full-diff review after the correction batch. Do not review only the latest commit.

5. **Risk-based severity.** Base P0-P3 severity on product, safety, privacy, contract, and verification impact. Presentation-only or incidental precision does not become blocking merely because the plan repeated it.

6. **Explicit deferral discipline.** Safely deferred edge cases require a recorded reason; P2 deferral still follows the existing owner-approval and follow-up rules.

Preserve the orchestrator implementation boundary, independent-review freshness, immutable review ranges, and all external-mutation authorisation gates.

## Validation scenarios

Exercise the revised templates against controlled examples covering:

- an open-ended measurement spike assigned to an unsuitable lower-tier implementer;
- the same spike converted into a bounded, machine-checkable experiment;
- a normal localized development issue where invariants and tests are sufficient;
- duplicated facts where one sibling remains stale after a change;
- a measurement command that emits plausible output after an upstream failure;
- repeated review findings sharing one root mechanism;
- a safely deferred presentation or shell-portability edge case;
- a safety-critical missing-versus-empty input that must not be deferred.

Use PR #143 only as historical evidence and scenario inspiration. Do not rewrite its handoff or require historical handoffs to satisfy the new template retroactively.

## Acceptance criteria

- [ ] Planner guidance distinguishes investigation, bounded experiments, development, safety work, and mechanical documentation.
- [ ] Model recommendations are driven by uncertainty and safety risk, with an explicit split-or-bound alternative when the intended implementer is not suited to investigation.
- [ ] Decision-critical, supporting, and incidental evidence have distinct requirements.
- [ ] Plans define facts once and make checklists/prompts reference canonical sections.
- [ ] Executable evidence is marked, fail-closed, shell-scoped, mechanically captured, and negative-path tested.
- [ ] Edge-case triage identifies what may be safely deferred and what must block.
- [ ] Development plans emphasize invariants, seams, and acceptance tests rather than unnecessary implementation transcription.
- [ ] Orchestrator guidance batches findings by root cause, triggers mechanism-level simplification, performs sibling sweeps, and re-reviews the complete corrected diff.
- [ ] Existing phase authorisation, reviewer read-only boundaries, two-PR lifecycle, and independent-review requirements remain intact.
- [ ] Controlled positive and negative scenarios are recorded.
- [ ] Applicable lint/tests, `git diff --check`, hygiene checks, and `WORKLOG.md` requirements pass for any later implementation PR.

## Out of scope

- Changing vault-cleaner product rules, parsers, reports, UI, server behavior, or runtime dependencies.
- Implementing or installing the reusable skills owned by #141.
- Replacing the two-PR workflow or relaxing phase authorisation gates.
- Giving planners, orchestrators, or reviewers broader mutation authority.
- Rewriting historical handoffs or reopening completed workflow tickets.
- Editing or merging PR #143 as part of this issue.

## Tracking

Type: `maintenance`, consistent with #124, #132, and #141.

No existing feature milestone fits this internal workflow-quality change. Leave it unassigned rather than creating a one-off milestone.

Add to [vault-cleaner project 3](https://github.com/users/tonym999/projects/3) with Status `Todo`.

**Comment by tonym999** [comment]
Sequencing note (owner decision, 2026-09-19): #163 lands before this issue. Both edit the model-selection step of `handoffs/templates/planner.md` and the findings sections of `handoffs/templates/orchestrator.md`, so planning for #144 should start from #163's merged state and fit its task-classification and uncertainty-driven model-selection wording around the role-based model roster and implementer ladder introduced there. #144 is not otherwise blocked. #141 follows both.
